name: Keep Render Service Alive

on:
  schedule:
    # Пинг каждые 10 минут (только в рабочие часы UTC)
    - cron: '*/10 6-22 * * 1-5'  # Пн-Пт, 6:00-22:00 UTC
    - cron: '*/15 * * * 0,6'     # Сб-Вс, каждые 15 минут

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -f https://multiagent-rag-api.onrender.com/health || echo "Service might be starting up"
      
      - name: Log Status
        run: echo "Pinged Render service at $(date)"
